stages:
  - prepare
  - test

build build-env image:
  stage: prepare
  script:
    - cd ci/build-env
    - docker build -t ${CI_REGISTRY_IMAGE}/build-env .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/build-env
  tags:
    - docker-host

build phoenix image:
  stage: prepare
  script:
    - cd ci/phoenix
    - docker build -t ${CI_REGISTRY_IMAGE}/phoenix:4.11 --build-arg HBASE_VERSION=1.3.1 --build-arg PHOENIX_VERSION=4.11.0-HBase-1.3 .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/phoenix:4.11
  tags:
    - docker-host

test:
  image: $CI_REGISTRY_IMAGE/build-env
  services:
    - name: $CI_REGISTRY_IMAGE/phoenix:4.11
      alias: phoenix
  variables:
    PHOENIXDB_TEST_DB_URL: http://phoenix:8765/
  script:
    - tox -e py27,py35
  tags:
    - docker
